const CATEGORIES_ACTION_TYPES = {
  FETCH_CATEGORIES_START: "categoies/FETCH_CATEGORIES_START",
  FETCH_CATEGORIES_SUCCESS: "categoies/FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_FAILED: "categoies/FETCH_CATEGORIES_FAILED",
};

export default CATEGORIES_ACTION_TYPES;
